# orchestra with docker-compose
version: "3"
services:
  coursematerial:
    image: devopsdockeruh/coursepage
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #link local docker socket with container socket
    container_name: watchtower

# remember to log out, then log in from the command line to your docker hub account!!!
